### PR TITLE
gardenctl info - print seeds in table

### PR DESCRIPTION
**Pull request by vpnachev**
**What this PR does / why we need it**:
gardenctl info - print seeds info in table

```bash
$ gardenctl info
Garden: my-garden
Seed                             Total                  Active                  Hibernated
----                             -----                  ------                  ----------
seed1                            13                     10                      3
seed2                            14                     1                       13
----                             -----                  ------                  ----------
TOTAL                            29                     11                      26
Unscheduled                      2
```

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement user
`gardenctl info` now is printing the shoots per seed in a table. 
```

### CODE REVIEW

**Comment by vpnachev** [comment]
Sure.
/status author-action
/needs changes
/hold

**Comment by ialidzhikov** [comment]
There is an output flag which defaults to yaml. It would be strange to run `g info --output=yaml` and to have a text output.

**Comment by DockToFuture** [comment]
This was a problem in the first place, the output flag did not work for json. We have to change that separatly.

**Pull request merged**
