### PR TITLE
aws.go az.go gcloud.go

### LINKED ISSUE #389: v0.22.0 gardenctl unable to operate against aws/gcp/azure cloud providers
**Describe the bug**

This bug is introduced in https://github.com/gardener/gardenctl/pull/368
Now the issue is (same for aws/gcp/azure):

1) when run some cloud provider command e.g. `gardenctl aws ec2 describe-instances`, the actually command running is `gardenctl aws aws ec2 describe-instances`, so the `aws` command will exit with error code.
The problem code is https://github.com/gardener/gardenctl/pull/368/commits/d5677ca1b31d3769881cb5dd608b95c22025813c#diff-35cfdbb008094fbcbebfc8909edc59f44d1290e38a3bdd9da5c08b5fadff1de7R90

the `args` already contains cloud provider command e.g. `aws` and in next line, `aws` is append again

2) even the 1) is fixed, `gardenctl aws ec2 describe-instances` will display nothing.

the problem code is https://github.com/gardener/gardenctl/pull/368/commits/d5677ca1b31d3769881cb5dd608b95c22025813c#diff-35cfdbb008094fbcbebfc8909edc59f44d1290e38a3bdd9da5c08b5fadff1de7R94

previous code will return command output but now it displays nothing
```
err := ExecCmd(nil, arguments, false, "AWS_ACCESS_KEY_ID="+string(accessKeyID[:]), "AWS_SECRET_ACCESS_KEY="+string(secretAccessKey[:]), "AWS_DEFAULT_REGION="+region, "AWS_DEFAULT_OUTPUT=text")
```

Above 1) and 2) issues applies for gcp/aws/azure

**To Reproduce**
1. target a gcp/aws/azure
2. gardenctl aws/gcp/azure
3. nothing is displayed

**Expected behavior**
error should not occur

**Screenshots**

**Gardenctl Version (please complete the following information):**
v0.22.0
**Additional context**

### LINKED ISSUE #395: Gardenctl ssh with aws doesn't work
**Describe the bug**
Gardenctl ssh with aws doesn't work. During step 1/4 of sshing to the node via gardenctl, it fails due to wrong aws-cli usage. 

**To Reproduce**
1. Which target was set 'gardenctl get target'
I targeted a shoot for whose project I am admin
2. Which command was entered [e.g. 'gardenctl show vpn-seed']
`gardenctl ssh <node_name>`
3. What was the output of the command 
```
Downloaded id_rsa key
Check Public IP
(1/4) Fetching data from target shoot cluster
2020/10/19 08:10:55 AWS CLI failed with usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument command: Invalid choice, valid choices are:
...
```

**Expected behavior**
Established ssh session to node.

**Gardenctl Version (please complete the following information):**
```
gardenctl:
		version     : v0.23.0
		build date  : 2020-10-16
		go version  : go1.14.9
		go compiler : gc
		platform    : darwin/amd64
``` 

** AWS CLI version
```
aws --version
aws-cli/2.0.56 Python/3.9.0 Darwin/19.6.0 source/x86_64
```

**Additional context**
`gardenctl shell <node_name>` works - so this bug is not really critical to me.

### PR DESCRIPTION
**Pull request by tedteng**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardenctl/issues/389
Fixes https://github.com/gardener/gardenctl/issues/395

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Comment by dansible** [comment]
I think for this to be merged, it would need to take into account the changes in the hotfix with trimming and cleaning up the arg list:
https://github.com/gardener/gardenctl/pull/390/files

**Comment by tedteng** [comment]
> I think for this to be merged, it would need to take into account the changes in the hotfix with trimming and cleaning up the arg list:
> https://github.com/gardener/gardenctl/pull/390/files

sure, didn't saw the PR already meged .will fetch the latest code and trimming and cleaning up the argllist

**Comment by tedteng** [comment]
AWS SSH and subcommand aws cli veirfy - PASS

```
gg aws -- --version                                
aws-cli/2.0.40 Python/3.8.5 Darwin/19.6.0 source/x86_64
```
```
gg ssh ip-10-250-26-3.eu-central-1.compute.internal                             

Warning:
Be aware that you are entering an untrusted environment!
Do not enter credentials or sensitive data within the ssh session that cluster owners should not have access to.

Downloaded id_rsa key
Check Public IP

(1/4) Fetching data from target shoot cluster
Data fetched from target shoot cluster.

(2/4) Setting up bastion host security group
Bastion host security group set up.

(3/4) Creating bastion host and node host security group
Bastion host instance i-007e588024f752b21 Initializing.

Bastion host instance running.
Opened SSH Port on Node.
Waiting 60 seconds for Bastion SSH port open
=> nc: connectx to 18.184.113.54 port 22 (tcp) failed: Connection refused

=> nc: connectx to 18.184.113.54 port 22 (tcp) failed: Connection refused

=> Connection to 18.184.113.54 port 22 [tcp/*] succeeded!

Opened SSH Port on Bastion
SSH gardener@18.184.113.54 => gardener@ip-10-250-26-3.eu-central-1.compute.internal
Warning: Permanently added '18.184.113.54' (ED25519) to the list of known hosts.
Warning: Permanently added 'ip-10-250-26-3.eu-central-1.compute.internal' (ED25519) to the list of known hosts.
  ____               _              _     _                  
 / ___| __ _ _ __ __| | ___ _ __   | |    _ _ __  _   ___  __
| |  _ / _` | '__/ _` |/ _ \ '_ \  | |   | | '_ \| | | \ \/ /
| |_| | (_| | | | (_| |  __/ | | | | |___| | | | | |_| |>  < 
 \____|\__,_|_|  \__,_|\___|_| |_| |_____|_|_| |_|\__,_/_/\_\
Garden Linux 11 (based on Debian GNU/Linux 11)               

Welcome to ip-10-250-26-3.eu-central-1.compute.internal  Mon Oct 19 06:32:15 UTC 2020
Linux #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 up 18 hours, 22 minutes
Load:  0.12, 0.19, 0.18 of 2CPUs  no iowait  no steal time
Free:  RAM 54.61%  Disk / 91.44% /usr 23.47% /boot/efi 100.00% 

ens5       10.250.26.3/19  fe80::4f:a1ff:fe1a:aec6/64  
tunl0       100.96.0.1/32                              


The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
_____________________________________________________________________
WARNING! Your environment specifies an invalid locale.
 The unknown environment variables are:
   LC_CTYPE=UTF-8 LC_ALL=
 This can affect your user experience significantly, including the
 ability to manage packages. You may install the locales by running:

 sudo dpkg-reconfigure locales

 and select the missing language. Alternatively, you can install the
 locales-all package:

 sudo apt-get install locales-all

To disable this message for all users, run:
   sudo touch /var/lib/cloud/instance/locale-check.skip
_____________________________________________________________________

$ 
```

**Comment by tedteng** [comment]
Az SSH & subcommand az cli -- **PASS**

```
gg az -- -h                                                      
Group
    az
```
```
gg ssh shoot--i333878--az-az-001-worker-bt6i6-z3-598c94d869-fpjj9
Warning:
Be aware that you are entering an untrusted environment!
Do not enter credentials or sensitive data within the ssh session that cluster owners should not have access to.

Downloaded id_rsa key
Check Public IP

(1/4) Fetching data from target shoot cluster
Standard
Data fetched from target shoot cluster.

(2/4) Configuring Azure
Opened SSH Port.

Create public ip
20.54.88.160
Waiting 5 s until public ip is available.

Add public ip to nic

Waiting 30 seconds until ports are open.
(3/4) Establishing SSH connection

Warning: Permanently added '20.54.88.160' (ED25519) to the list of known hosts.
  ____               _              _     _                  
 / ___| __ _ _ __ __| | ___ _ __   | |    _ _ __  _   ___  __
| |  _ / _` | '__/ _` |/ _ \ '_ \  | |   | | '_ \| | | \ \/ /
| |_| | (_| | | | (_| |  __/ | | | | |___| | | | | |_| |>  < 
 \____|\__,_|_|  \__,_|\___|_| |_| |_____|_|_| |_|\__,_/_/\_\
Garden Linux 11 (based on Debian GNU/Linux 11)               
```

**Comment by tedteng** [comment]
GCP SSH -Pass but gcloud cli -failure. 

```
gg ssh shoot--i333878--az-az-001-worker-bt6i6-z3-598c94d869-fpjj9
Warning:
Be aware that you are entering an untrusted environment!
Do not enter credentials or sensitive data within the ssh session that cluster owners should not have access to.

Downloaded id_rsa key
Check Public IP

(1/4) Fetching data from target shoot cluster
Standard
Data fetched from target shoot cluster.

(2/4) Configuring Azure
Opened SSH Port.

Create public ip
20.54.93.79
Waiting 5 s until public ip is available.

Add public ip to nic

Waiting 30 seconds until ports are open.
(3/4) Establishing SSH connection

Warning: Permanently added '20.54.93.79' (ED25519) to the list of known hosts.
  ____               _              _     _                  
 / ___| __ _ _ __ __| | ___ _ __   | |    _ _ __  _   ___  __
| |  _ / _` | '__/ _` |/ _ \ '_ \  | |   | | '_ \| | | \ \/ /
| |_| | (_| | | | (_| |  __/ | | | | |___| | | | | |_| |>  < 
 \____|\__,_|_|  \__,_|\___|_| |_| |_____|_|_| |_|\__,_/_/\_\
Garden Linux 11 (based on Debian GNU/Linux 11)               

Welcome to shoot--i333878--az-az-001-worker-bt6i6-z3-598c94d869-fpjj9.ku0di1l4wfdutovlmztclf00lc.fx.internal.cloudapp.net  Mon Oct 19 06:51:41 UTC 2020
Linux #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 up 17 minutes
Load:  3.49, 3.08, 2.30 of 1CPUs  23.19% iowait  no steal time
Free:  RAM 6.45%  Disk / 92.54% /usr 28.08% /boot/efi 100.00% /mnt/resource 94.37% 

eth0       10.250.0.4/16  fe80::20d:3aff:fedd:c955/64  


The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Mon Oct 19 06:41:45 2020 from 180.166.22.232
```

**Comment by tedteng** [comment]
after checked at least from v21 the gcloud issue already exist it will open the issue ticket. 

./gardenctl-darwin-amd64 gcloud compute instances list
ERROR: (gcloud.auth.activate-service-account) Missing required argument [ACCOUNT]: An account is required when using .p12 keys
image

**Comment by tedteng** [comment]
The .ci/test is only a temporary solution before we found a new solution as we lack knowledge about ginkgo & gomega now to achieve the goal. I hope we can use ginkgo & gomega in the future. 

to use test shell script on local 
`.ci/test local`

**Review by dansible — APPROVED** [review]

**Comment by neo-liang-sap** [comment]
/LGTM
i haven't test it but based on author's test and discussion with @dansible i will merge it

**Pull request merged**
