### PR TITLE
Vpn shoot logs

### LINKED ISSUE #358: Enable `gardenctl logs vpn-shoot`
Enable `gardenctl logs vpn-shoot`

### PR DESCRIPTION
**Pull request by jguipi**
**What this PR does / why we need it**:
add gardenctl logs vpn-shoot to display vpn-shoot logs

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardenctl/issues/358

**Special notes for your reviewer**:

**Release note**:
add `gardenctl logs vpn-shoot` to display vpn-shoot logs

### CODE REVIEW

**Comment by gardener-robot-ci-1** [comment]
Thank you @jguipi for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by jguipi** [comment]
For some reason @tedteng I'm not able to see the empty commit in the history. not able to remove it

**Comment by neo-liang-sap** [comment]
@jguipi , the empty commit is still there, 
image

I suggest you 
1) check out latest master branch
2) check out a new branch based on 1)
3) git cherry-pick your commit to 2)
4) re-submit a PR

As i'm going to be vacation from Oct 1 to Oct 8, could you please consult with @dansible or @jfortin-sap to get this work?
thanks!

**Comment by tedteng** [comment]
you can either use the way as mention above or force commit after merge..
As you don't have any comments after view this time, the force commit (git push -f )not break the view comments.

**Pull request closed without merging**
