### PR TITLE
Vpn shoot logs v2

### LINKED ISSUE #358: Enable `gardenctl logs vpn-shoot`
Enable `gardenctl logs vpn-shoot`

### PR DESCRIPTION
**Pull request by jguipi**
**What this PR does / why we need it**:
add gardenctl logs vpn-shoot to display vpn-shoot logs

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardenctl/issues/358

**Special notes for your reviewer**:

**Release note**:
add `gardenctl logs vpn-shoot` to display vpn-shoot logs

### CODE REVIEW

**Comment by gardener-robot-ci-2** [comment]
Thank you @jguipi for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by jguipi** [comment]
Those test are successful `.ci/test` `/ .ci/build`

but this one `/ .ci/check` return the following error 
image

Those lint error seems to have been there before my PR and looks like we can skip them since.
a lot of them mentioned that we should use `fmt.Fprintf instead of fmt.Fprintln` If I'm not wrong it's important to keep the  `Fprintln` since we always want to print the output on a new line.

**Comment by neo-liang-sap** [comment]
Hi @jguipi ,
From Concourse CI build the `.ci/build` `.ci/check` `.ci/test` are all failing, please fix them, otherwise this PR could not be approved / merged.
image

Another point, it is always nice to have only one commit in one PR (off course when someone give some review comments, you have some fix pushed, it's good to have several commit as history for reviewer to review) but when a PR ready for merge, it's always good to have only one commit in one PR, which makes merging history of master branch looks nice.
You could achieve this by 
 https://www.internalpointers.com/post/squash-commits-into-one-git
https://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git-squash/13231 

If you have question on this you may ask @jfortin-sap @dansible as i'm currently on vacation.
Thanks!
-Neo

**Review by neo-liang-sap — CHANGES_REQUESTED** [review]
image
Hi @jguipi ,
From coucourse CI build result ,  build / test/check are all failing, please fix them otherwise this PR could not be approved / merged
Another point, it's always nice to have one commit in one PR so when merging it looks nice in merge history of master branch, you may achieve this by  https://www.internalpointers.com/post/squash-commits-into-one-git
https://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git-squash/13231 
You could ping @jfortin-sap @dansible for more information regarding this as i'm on vacation.
Thanks!
-Neo

**Pull request closed without merging**
