### PR TITLE
add getTargetMapInfo getTargetName isTargeted getFromTargetInfo

### LINKED ISSUE #312: Gardenctl ssh fails when targeting a non unique shoot name
**Describe the bug**

Gardenctl is unable to ssh into a node if there are multiple shoots in one gardener instance with the same name.
When running `gardenctl ssh` on a shoot with a non unique name, gardenctl is unable to determine the correct context and tries to access the seed of the other shoot: `Error: stat /Users/xxx/.garden/cache/live/seeds/other-seed/kubeconfig.yaml: no such file or directory`

**To Reproduce**
Create 2 shoots with the same name in different projects
1. target one of the shoots.
2. `gardenctl ssh`
3. `Error: stat /Users/xxx/.garden/cache/live/seeds/other-seed/kubeconfig.yaml: no such file or directory`

**Expected behavior**
Gardenctl should be able ssh into a node even if there are multiple shoots with the same name

**Gardenctl Version (please complete the following information):**
 - v0.21.0

**Additional context**
cc @DockToFuture please correct or add your observations to the description.

### PR DESCRIPTION
**Pull request by tedteng**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardenctl/issues/312

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Fixed issue that ssh command was not working in case there were shoots with the same name in different projects
```

### CODE REVIEW

**Comment by neo-liang-sap** [comment]
Hi @petersutter , could you please take a look at this PR when you have time? i'm not fully involved in discussion between you and @tedteng , thanks! 
My understanding of this PR is a increment to https://github.com/gardener/gardenctl/pull/319 (with several fix in infra.go), do correct me if i was wrong. 
Generally LGTM
Thanks!
-Neo

**Review by petersutter — APPROVED** [review]
/lgtm

please note that I have removed the release note in #319 as this PR was meanwhile reverted and replaced with this PR which includes the same release note. Otherwise the release note would appear twice when releasing.
The release notes handling can't recognize if the changes in PR #319 have been reverted in the meantime, that's why they have to be manually removed from the PR.

**Comment by neo-liang-sap** [comment]
noted with great thanks @petersutter ! i will also take care about this point in future revert occurrence

**Review by neo-liang-sap — APPROVED** [review]
/lgtm and merge based on review comments from @petersutter and concourse CI testing results
thanks for the PR

**Pull request merged**
