### PR TITLE
Limit SSH node security group to Bastion IP

### LINKED ISSUE #248: Node SSH security group enhance
**Describe the bug**
Current, The Bastion Server only allows user's Public IP to access now.  shoot-node create security group open port 22 0.0.0.0/0 to allow Bastion Server access when using `gardenctl ssh`. 

However, the SSH security group may remain in shoot-node when `gardenctl ssh` unexpected exit. which means no restriction to access shoot-node. 

What about use Internal IP of Bastion Server instead of 22 0.0.0.0/0 in SSH security group of shoot-node to minimize the security risk 
 
GCP/AZ/AWS

### PR DESCRIPTION
**Pull request by jfortin-sap-zz**
**What this PR does / why we need it**:
Limit SSH node security group to Bastion IP
**Which issue(s) this PR fixes**:
Fixes #248 

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Limit SSH node security group to Bastion IP
```

### CODE REVIEW

**Comment by gardener-robot-ci-3** [comment]
Thank you @jfortin-sap for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by tedteng** [comment]
nice, how about also include the AZ and GCP

**Comment by jfortin-sap** [comment]
@tedteng AZ/GCP is already fine

**Comment by jfortin-sap** [comment]
@neo-liang-sap done

**Review by neo-liang-sap — APPROVED** [review]

**Pull request merged**
