### PR TITLE
ssh param providerid

### LINKED ISSUE #406: ssh using machine cloud provider id
**Feature**
ssh using machine cloud provider id when not available from (g ssh).

### PR DESCRIPTION
**Pull request by jfortin-sap-zz**
**What this PR does / why we need it**:
ssh to machine specifying machine provider id (g ssh --providerid)
**Which issue(s) this PR fixes**:
Fixes #406 

**Special notes for your reviewer**:

**Release note**:

```improvement operator
ssh to machine specifying machine provider id (g ssh --providerid)
```

### CODE REVIEW

**Comment by dansible** [comment]
The pipeline build is failing at the lint check:
```
pkg/cmd/ssh_aws.go:100:2: ineffectual assignment to `command` (ineffassign)

	command := make([]string, 0)

	^

pkg/cmd/ssh_azure.go:84:2: ineffectual assignment to `command` (ineffassign)

	command := make([]string, 0)

	^

pkg/cmd/ssh_gcp.go:89:2: ineffectual assignment to `command` (ineffassign)

	command := make([]string, 0)
```

**Comment by dansible** [comment]
The code also produces `too many errors` 😅 

```
$ go run cmd/gardenctl/main.go ssh --providerid i-0861270e276e3136b
# golang.org/x/text/unicode/bidi
vendor/golang.org/x/text/unicode/bidi/tables12.0.0.go:8:7: UnicodeVersion redeclared in this block
	previous declaration at vendor/golang.org/x/text/unicode/bidi/tables11.0.0.go:8:24
vendor/golang.org/x/text/unicode/bidi/tables12.0.0.go:12:5: xorMasks redeclared in this block
	previous declaration at vendor/golang.org/x/text/unicode/bidi/tables11.0.0.go:12:5
vendor/golang.org/x/text/unicode/bidi/tables12.0.0.go:19:20: (*bidiTrie).lookup redeclared in this block
	previous declaration at vendor/golang.org/x/text/unicode/bidi/tables11.0.0.go:19:6
vendor/golang.org/x/text/unicode/bidi/tables12.0.0.go:81:20: (*bidiTrie).lookupUnsafe redeclared in this block
	previous declaration at vendor/golang.org/x/text/unicode/bidi/tables11.0.0.go:81:6
vendor/golang.org/x/text/unicode/bidi/tables12.0.0.go:104:20: (*bidiTrie).lookupString redeclared in this block
	previous declaration at vendor/golang.org/x/text/unicode/bidi/tables11.0.0.go:104:6
vendor/golang.org/x/text/unicode/bidi/tables12.0.0.go:166:20: (*bidiTrie).lookupStringUnsafe redeclared in this block
	previous declaration at vendor/golang.org/x/text/unicode/bidi/tables11.0.0.go:166:6
vendor/golang.org/x/text/unicode/bidi/tables12.0.0.go:187:6: bidiTrie redeclared in this block
	previous declaration at vendor/golang.org/x/text/unicode/bidi/tables11.0.0.go:187:6
vendor/golang.org/x/text/unicode/bidi/tables12.0.0.go:189:6: newBidiTrie redeclared in this block
	previous declaration at vendor/golang.org/x/text/unicode/bidi/tables11.0.0.go:189:26
vendor/golang.org/x/text/unicode/bidi/tables12.0.0.go:203:5: bidiValues redeclared in this block
	previous declaration at vendor/golang.org/x/text/unicode/bidi/tables11.0.0.go:203:5
vendor/golang.org/x/text/unicode/bidi/tables12.0.0.go:1802:5: bidiIndex redeclared in this block
	previous declaration at vendor/golang.org/x/text/unicode/bidi/tables11.0.0.go:1767:5
vendor/golang.org/x/text/unicode/bidi/tables12.0.0.go:166:20: too many errors
# golang.org/x/text/unicode/norm
vendor/golang.org/x/text/unicode/norm/tables12.0.0.go:11:2: Version redeclared in this block
	previous declaration at vendor/golang.org/x/text/unicode/norm/tables11.0.0.go:11:12
vendor/golang.org/x/text/unicode/norm/tables12.0.0.go:17:2: MaxTransformChunkSize redeclared in this block
	previous declaration at vendor/golang.org/x/text/unicode/norm/tables11.0.0.go:17:46
vendor/golang.org/x/text/unicode/norm/tables12.0.0.go:20:5: ccc redeclared in this block
	previous declaration at vendor/golang.org/x/text/unicode/norm/tables11.0.0.go:20:5
vendor/golang.org/x/text/unicode/norm/tables12.0.0.go:31:2: firstMulti redeclared in this block
	previous declaration at vendor/golang.org/x/text/unicode/norm/tables11.0.0.go:31:26
vendor/golang.org/x/text/unicode/norm/tables12.0.0.go:32:2: firstCCC redeclared in this block
	previous declaration at vendor/golang.org/x/text/unicode/norm/tables11.0.0.go:32:26
vendor/golang.org/x/text/unicode/norm/tables12.0.0.go:33:2: endMulti redeclared in this block
	previous declaration at vendor/golang.org/x/text/unicode/norm/tables11.0.0.go:33:26
vendor/golang.org/x/text/unicode/norm/tables12.0.0.go:34:2: firstLeadingCCC redeclared in this block
	previous declaration at vendor/golang.org/x/text/unicode/norm/tables11.0.0.go:34:26
vendor/golang.org/x/text/unicode/norm/tables12.0.0.go:35:2: firstCCCZeroExcept redeclared in this block
	previous declaration at vendor/golang.org/x/text/unicode/norm/tables11.0.0.go:35:26
vendor/golang.org/x/text/unicode/norm/tables12.0.0.go:36:2: firstStarterWithNLead redeclared in this block
	previous declaration at vendor/golang.org/x/text/unicode/norm/tables11.0.0.go:36:26
vendor/golang.org/x/text/unicode/norm/tables12.0.0.go:37:2: lastDecomp redeclared in this block
	previous declaration at vendor/golang.org/x/text/unicode/norm/tables11.0.0.go:37:26
vendor/golang.org/x/text/unicode/norm/tables12.0.0.go:37:2: too many errors
```

**Comment by jfortin-sap** [comment]
@dansible Your doing something wrong, the code is for --providerid and not coded to respond to "providerid". We will look into it tomorrow together.

**Comment by dansible** [comment]
Thanks for the changes 👍 
Let's wait for https://github.com/gardener/gardenctl/pull/467 to be merged which should fix the AWS issues and we can merge this

**Comment by neo-liang-sap** [comment]
i will wait for another day to see any more review for https://github.com/gardener/gardenctl/pull/467 - if no reviews coming i will merge https://github.com/gardener/gardenctl/pull/467

**Comment by neo-liang-sap** [comment]
per @jfortin-sap request in slack i will merge this PR

**Pull request merged**
