### PR TITLE
Change the way the gardenctl displays logs from loki

### PR DESCRIPTION
**Pull request by Kristian-ZH**
**What this PR does / why we need it**:
1. Change the default value of `tail` flag from 200 to 1000, because if someone does not know about this flag, he will think that there is an issue with gardenctl logs/loki  because very few logs are displayed

2. Change the way the gardenctl displays logs from loki.
Now the logs will be visualised in the following way:
```
=============================================================================================
Pod Name kube-controller-manager-fsdfsd-fsdfs,  Container Name: kube-controller-manager, DockerID: dbcb643a5dfbbd12e8dbf50e497dab8
=============================================================================================
// logs
// logs
// logs
=============================================================================================
Pod Name kube-controller-manager-fsdfsd-fsdfs, Container Name: kube-controller-manager, DockerID: fsdfsdgsfsgsfsfsfs
=============================================================================================
//logs
//logs
//logs
=============================================================================================
Pod Name side-car-fsdfsd-fsdfs, Container Name: kube-controller-side-car-container, DockerID: 31241321413132
=============================================================================================
// logs
// logs
// logs
```

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
New format of the `gardenctl logs --loki` command
```

### CODE REVIEW

**Review by tedteng — COMMENTED** [review]
It looks good. 
just one comment, I am not clear the docker id in there. Is that represent history Pod?  eg.  api-server has been restarted, the DockerID to distinguish previous Pod and current live Pod?  if Yes, is it possible to display the Pod name to identify it as well ?
```
============================================================================================
Container Name: kube-controller-manager, DockerID: dbcb643a5dfbbd12e8dbf50e497dab8
=============================================================================================
// logs
// logs
// logs
=============================================================================================
Container Name: kube-controller-manager, DockerID: fsdfsdgsfsgsfsfsfs
=============================================================================================```

**Comment by Kristian-ZH** [comment]
> Is that represent history Pod? eg. api-server has been restarted, the DockerID to distinguish previous Pod and current live Pod?

Yes correct. In each container there is a running docker process. DockerID represents this process. If the DockerID is changed, it means that the the container has been restarted.

 > is it possible to display the Pod name to identify it as well ?
Thats a good idea. It is possible and if the complexity of the code will not be increased much, I will add it.
Will try it today.

**Comment by Kristian-ZH** [comment]
did the changes

**Comment by Kristian-ZH** [comment]
Аlso to emphasise that the current `gardenctl logs --loki` command does not work correctly. It sorts logs by stream, not by container as this PR does.
Each stream includes `Secerity` label and this means that all logs with severity=Error will be displayed on one place, with severity=Info on another and so on.

**Review by tedteng — APPROVED** [review]
lgtm

**Comment by neo-liang-sap** [comment]
Per discussion with @Kristian-ZH i will merge this PR and trigger a minor release

**Pull request merged**
