### PR TITLE
replace target.Target

### PR DESCRIPTION
**Pull request by tedteng**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardenctl/issues/347

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Comment by petersutter** [comment]
I have quickly scrolled over the changes (as this PR is still in draft) and I really like the changes. Much cleaner now. I'm looking forward for the PR to be ready.

**Comment by tedteng** [comment]
got one block. Not sure the root casue yet, I am feeling it seems related with `target_test.go` mocking method input.  need more research about the usage of ginkgo. 

in line 986 if I change  `if len(target.Stack()) < 1`  to `if isTargeted("garden")`, the target_test.go failure ``
```golang
func projectWrapper(targetReader TargetReader, targetWriter TargetWriter, configReader ConfigReader, ioStreams IOStreams, args []string) error {
	if len(args) != 2 {
		return errors.New("command must be in the format: target project NAME")
	}
	target := targetReader.ReadTarget(pathTarget)
	if len(target.Stack()) < 1 {
		return errors.New("no garden cluster targeted")
	}
```

```
[It] targeting project
  /Users/i333878/Work/tedteng/gardenctl/pkg/cmd/target_test.go:63
open : no such file or directory

Ginkgo ran 1 suite in 6.642496809s
Test Suite Failed
```

**Comment by tedteng** [comment]
@petersutter  Do you have any idea how to handle this during .ci/test?
```golang
[It] should pass on get seed
  /Users/i333878/Work/tedteng/gardenctl/pkg/cmd/get_test.go:182
open : no such file or directory
```

Take a example `get.go` and `get_test.go` 
It seems `command.SetArgs([]string{"seed"})` in get_test.go need match with `target.Stack()[1].Kind == "seed"` in `get.go` otherwise failure the test

```golang
func getSeed(name string, targetReader TargetReader, ioStreams IOStreams) error {
	target := targetReader.ReadTarget(pathTarget)
	if name == "" {
		if len(target.Stack()) > 1 && isTargeted("seed") { //target.Stack()[1].Kind == "seed"
			name = target.Stack()[1].Name
		} else if len(target.Stack()) > 1 && target.Stack()[1].Kind == "project" && len(target.Stack()) == 3 {
			name = getSeedForProject(target.Stack()[2].Name)
		} else {
			return errors.New("no seed targeted or shoot targeted")
		}
	}
```

**Comment by petersutter** [comment]
FYI, in this comment I make multiple suggestions, one building up on the other and improving the code even further. The final suggestion is at the bottom. The code is not tested and just written down but you should get the idea..

----
Regarding this piece of code:
```golang
func getSeed(name string, targetReader TargetReader, ioStreams IOStreams) error {
	target := targetReader.ReadTarget(pathTarget)
	if name == "" {
		if len(target.Stack()) > 1 && isTargeted("seed") { //target.Stack()[1].Kind == "seed"
			name = target.Stack()[1].Name
		} else if len(target.Stack()) > 1 && target.Stack()[1].Kind == "project" && len(target.Stack()) == 3 {
			name = getSeedForProject(target.Stack()[2].Name)
		} else {
			return errors.New("no seed targeted or shoot targeted")
		}
	}
        // ...
```

Remove the function `getSeedForProject` and adapt the callers to use `getFromTargetInfo("seed")` instead (`targetInfo` needs to be initialized by calling `getTargetMapInfo` call of course, if not already done). 

I think you can change the code as following (not tested)
```go
func getSeed(name string, targetReader TargetReader, ioStreams IOStreams) error {
	target := targetReader.ReadTarget(pathTarget)
	if name == "" {
		name = getFromTargetInfo("seed") // <--------------------------------------------------
	}
	client, err := target.K8SClientToKind(TargetKindGarden)
	if err != nil {
		return err
	}
	gardenClientset, err := target.GardenerClient()
	if err != nil {
		return err
	}
	seed, err := gardenClientset.CoreV1beta1().Seeds().Get(name, metav1.GetOptions{})
	if err != nil {
		return err
	}
	kubeSecret, err := client.CoreV1().Secrets(seed.Spec.SecretRef.Namespace).Get(seed.Spec.SecretRef.Name, metav1.GetOptions{})
	if err != nil {
		return err
	}
	if outputFormat == "yaml" {
```
Even better suggestion:
- rename the getSeed function to what it really does -> it prints the seed kubeconfig
- drop the name parameter, it's not needed when using `getFromTargetInfo("seed")`
- introduce getSeedObject function
```go
func printSeedKubeconfig(targetReader TargetReader, ioStreams IOStreams) error {
	seed, err := getSeedObject(targetReader)
	if err != nil {
		return err
	}
	kubeSecret, err := client.CoreV1().Secrets(seed.Spec.SecretRef.Namespace).Get(seed.Spec.SecretRef.Name, metav1.GetOptions{})
	if err != nil {
		return err
	}
	if outputFormat == "yaml" {
        // ...
}

// not sure if we need to pass the target reader or if we can get it otherwise...
func getSeedObject(targetReader TargetReader,) (*v1beta1.Seed, error) {
	name = getFromTargetInfo("seed")
	target := targetReader.ReadTarget(pathTarget)
	client, err := target.K8SClientToKind(TargetKindGarden)
	if err != nil {
		return nil, err
	}
	gardenClientset, err := target.GardenerClient()
	if err != nil {
		return nil, err
	}
	return gardenClientset.CoreV1beta1().Seeds().Get(name, metav1.GetOptions{})
}
```

**Final suggestion:** 
And I would go even further and change printSeedKubeconfig to getSeedKubeconfig and handle the response from the caller, to get rid of all the duplicate yaml/json handling and do it only once from the caller
```go
	if outputFormat == "yaml" {
		// ...
	} else if outputFormat == "json" {
                // ...
	}
```

```go
func getSeedKubeconfig(targetReader TargetReader, ioStreams IOStreams) (string, error) {
	seed, err := getSeedObject(targetReader)
	if err != nil {
		return err
	}
	kubeSecret, err := client.CoreV1().Secrets(seed.Spec.SecretRef.Namespace).Get(seed.Spec.SecretRef.Name, metav1.GetOptions{})
	if err != nil {
		return err
	}
	return kubeSecret.Data["kubeconfig"], nil
}

// NewGetCmd returns a new get command.
func NewGetCmd(targetReader TargetReader, configReader ConfigReader,
	kubeconfigReader KubeconfigReader, kubeconfigWriter KubeconfigWriter, ioStreams IOStreams) *cobra.Command {
	cmd := &cobra.Command{
		Use:          "get [(garden|project|seed|shoot|target) <name>]",
		Short:        "Get single resource instance or target stack, e.g. CRD of a shoot (default: current target)\n",
		SilenceUsage: true,
		RunE: func(cmd *cobra.Command, args []string) (err error) {
			if len(args) < 1 || len(args) > 2 {
				return errors.New("command must be in the format: get [(garden|project|seed|shoot|target) <name>]")
			}
			var kubeconfig string
			switch args[0] {
			case "project":
				kubeconfig, err = getProjectKubeconfig(targetReader)
				if err != nil {
					return err
				}
			case "garden":
				// ... you get the idea ...
			case "seed":
				kubeconfig, err = getSeedKubeconfig(targetReader)
				if err != nil {
					return err
				}
			case "shoot":
				// ... you get the idea ...
			case "target":
				// ... you get the idea ...
			default:
				fmt.Fprint(ioStreams.Out, "command must be in the format: get [project|garden|seed|shoot|target] + <NAME>")
				return nil // or exit with error?
			}
			if outputFormat == "yaml" {
				// print out as yaml
			} else if outputFormat == "json" {
				// print out as json
			}

			return nil
		},
		ValidArgs: []string{"project", "garden", "seed", "shoot", "target"},
	}

	return cmd
}
```

When you have done the refactoring we can take another look if the test still fails and continue from there

**Comment by tedteng** [comment]
Hi @petersutter  Thanks for your advice. Busy on another task for the past two working days, I just back to work on this task today and have one thought during refactoring. 

as get garden/seed/shoot only print kubeconfig,  Take an example for here to print garden kubeocnfig. the kubeconfig get from local directly then output 

https://github.com/gardener/gardenctl/blob/dc3d2726383a451ad8f6682555c8b5c7790c55d2/pkg/cmd/get.go#L156-L162

To remove duplicated code, we can re-use this method and print it directly?  same for seed and shoot? https://github.com/gardener/gardenctl/blob/dc3d2726383a451ad8f6682555c8b5c7790c55d2/pkg/cmd/miscellaneous.go#L85,  WDYT ?

**Comment by petersutter** [comment]
Hi @tedteng, not sure I could follow you 100% but if you can remove duplicate code with your suggestion and re-use existing functionality this sounds good

**Comment by tedteng** [comment]
@petersutter  The refactor will cover a lot of files. It may more complex in one PR. so I decided open the PR one by one for individually will close this PR later

the get refactors https://github.com/gardener/gardenctl/pull/400 here, welcome any feedback and concerns. I will continue to search for the test part tomorrow.

**Pull request closed without merging**
