### PR TITLE
list orphaned resources

### PR DESCRIPTION
**Pull request by jfortin-sap-zz**
**What this PR does / why we need it**:
Identify cloud provider resources not found in terraform state
**Which issue(s) this PR fixes**:
Fixes #252 

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Identify cloud provider resources not found in terraform state
```

### CODE REVIEW

**Comment by gardener-robot-ci-3** [comment]
Thank you @jfortin-sap for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by neo-liang-sap** [comment]
@jfortin-sap shall we add some limitation (as it's only works for AWS for now) in Release Note?

**Comment by tedteng** [comment]
no idea why, but it seems not working 
image

**Comment by jfortin-sap** [comment]
@tedteng It's correct If you try to delete the shoot but there is a bastion, bastion resource by default is not included in the terraform state.

**Comment by jfortin-sap** [comment]
I need to add modifications to make the function testable. Closing this PR and will re-open one soon.

**Pull request closed without merging**
