### PR TITLE
pr conflict-check

### LINKED ISSUE #452: PR conflicts not watched
**Describe the bug**
The PRs may affected by one PR merged.  however, the conflict msg never notice the owner either mail or github comment.

I want to use an action to watch the PR conflict and mention the owner in the comment when conflict occurs. 

image

### PR DESCRIPTION
**Pull request by tedteng**
**What this PR does / why we need it**:
code conflict check and notify code owner

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardenctl/issues/452

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Review by dansible — APPROVED** [review]
Nice feature 👍

**Comment by tedteng** [comment]
this Pr for conflict-check only

**Comment by neo-liang-sap** [comment]
please, always wait for all checks passed before merging, i've seen scenario where first four checks all passed but failed at last one. Thanks!
https://sap-ti.slack.com/archives/CBVQLMS6N/p1606270903441300?thread_ts=1606267803.440500&cid=CBVQLMS6N

**Comment by tedteng** [comment]
sure np, I also saw the scenario first four checks all passed but failed at last one.

I can't remember the purpose for the first one `publish` in this scenario, it may related with CI/CD,  and I noticed it a failure for a long time. Let me know how to handle `publish` failure/pending issue instead of waiting for failure status.

**Pull request merged**
