### PR TITLE
inspect and refactor ls.go

### LINKED ISSUE #328: Sanitize user input in ls.go & operate.go
**Describe the bug**

Sanitize user input when executing local commands as much as possible

This is one of the sub-task for ticket https://github.com/gardener/gardenctl/issues/267

### PR DESCRIPTION
**Pull request by andrei-panov**
**What this PR does / why we need it**:
code cleanup
**Which issue(s) this PR fixes**:
Fixes #328 

**Special notes for your reviewer**:
ls.go only inspected with this PR. No additional sanitization is required. All changes should be served as refactoring.

**Release note**:
```improvement operator
new tested method `cmd.PrintoutObject` can be used to print structures in YAML or JSON format to passed io.Writer
```

### CODE REVIEW

**Review by dansible — DISMISSED** [review]
lgtm

**Comment by dansible** [comment]
Hi @andrei-panov, thanks for the PR. The changes look good 👍 

Can you add a release note to the PR description as in the template? This should include info for the `PrintoutObject` function and testing

**Review by petersutter — APPROVED** [review]
/lgtm

**Comment by andrei-panov** [comment]
@dansible all planned changes for the related issue are in place, please approve. The release noted updated.

**Review by dansible — APPROVED** [review]

**Pull request merged**
