### PR TITLE
fix nc hanging and cleanup

### LINKED ISSUE #240: SSH unstable
**Describe the bug**

I am unsuccessful in trying to use `gardenctl ssh` with the version from the master branch (has [latest commit included]()).

**To Reproduce**
 - on an AWS VM in region `eu-north-1` using instance type t3.xLarge

```
./gardenctl-darwin-amd64 ssh ip-10-250-17-222.eu-north-1.compute.internal

Warning:
Be aware that you are entering an untrusted environment!
Do not enter credentials or sensitive data within the ssh session that cluster owners should not have access to.

Downloaded id_rsa key
Check Public IP

(1/4) Fetching data from target shoot cluster
Data fetched from target shoot cluster.

(2/4) Setting up bastion host security group
Bastion host security group set up.
Opened SSH Port on Node.

(3/4) Creating bastion host
Bastion host instance i-011b9d6c4209a78aa Initializing.

Bastion host instance running.
Waiting SSH port open on Bastion
```
The command is hanging indefinitely because the internal command is not succeeding and no timeout is configured:

```
nc  -rz -w 5 <bastion-public-ip> 22
```
 

To make it worse, when killing the process with CTRL + C ( SIGINT) - the process does not seem to have a proper signal handler installed and terminates without cleaning the resources.

**Expected behavior**

- ssh connection works
- there is a timeout for the `nc` command - why did it not work?
- the resources are being cleaned up on SIGINT

**Screenshots**

Also the bastion instance is showing this status after a while:

image

**Gardenctl Version (please complete the following information):**
 - Version/Commit [7e7d8ba7666acce5360396907c29b251a5c33b51]

**Additional context**
Tried it multiple times today and it did not work.

### PR DESCRIPTION
**Pull request by tedteng**
**What this PR does / why we need it**:
fix nc command hanging
fix nc timeout 
resource clean up after nc timeout 

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardenctl/issues/240

**Special notes for your reviewer**:
@danielfoehrKn , Please let me know whether this can fix the issue. 
one more thing the Public IP maybe change and binding with the security group as the latest update, so I am assuming there not any previous bastion security group remaining in the AWS. 

**Release note**:

```improvement operator
1. fix nc command hanging and timeout. 2. cleaned resource up after nc command timeout.
```

### CODE REVIEW

**Comment by tedteng** [comment]
Tesing for timeout and cleanup

```
Downloaded id_rsa key
Check Public IP

(1/4) Fetching data from target shoot cluster
Data fetched from target shoot cluster.

(2/4) Setting up bastion host security group
Bastion host security group set up.
Opened SSH Port on Node.

(3/4) Creating bastion host
Bastion host instance i-065b451a853e9282b Initializing.

Bastion host instance running.
=>
=>
=>
=>
=>
=>
SSH Port Open on Bastion TimeOut
(4/4) Cleanup
Cleaning up bastion host configurations...

Starting cleanup

  (1/3) Cleaning up bastion host instance
TERMINATINGINSTANCES	i-065b451a853e9282b
CURRENTSTATE	32	shutting-down
PREVIOUSSTATE	16	running

  (2/3) Close SSH Port on Node.
  Closed SSH Port on Node.

  (3/3) Clean up bastion host security group


Bastion host configurations successfully cleaned up.
```

**Comment by tedteng** [comment]
Expect result Testing 

Downloaded id_rsa key
Check Public IP

(1/4) Fetching data from target shoot cluster
Data fetched from target shoot cluster.

(2/4) Setting up bastion host security group
Bastion host security group set up.
Opened SSH Port on Node.

(3/4) Creating bastion host
Bastion host instance i-05b9ee39ebb141e95 Initializing.

Bastion host instance running.
nc: connectx to 18.156.193.166 port 22 (tcp) failed: Connection refused

nc: connectx to 18.156.193.166 port 22 (tcp) failed: Connection refused

Connection to 18.156.193.166 port 22 [tcp/*] succeeded!

Opened SSH Port on Bastion
SSH gardener@18.156.193.166 => gardener@ip-10-250-8-212.eu-central-1.compute.internalWarning: Permanently added '18.156.193.166' (ED25519) to the list of known hosts.
  ____               _              _     _
 / ___| __ _ _ __ __| | ___ _ __   | |    _ _ __  _   ___  __
| |  _ / _` | '__/ _` |/ _ \ '_ \  | |   | | '_ \| | | \ \/ /
| |_| | (_| | | | (_| |  __/ | | | | |___| | | | | |_| |>  <
 \____|\__,_|_|  \__,_|\___|_| |_| |_____|_|_| |_|\__,_/_/\_\
Garden Linux 11 (based on Debian GNU/Linux 11)

**Comment by neo-liang-sap** [comment]
lgtm
@gardener/gardenctl-maintainers any comments on this PR?

**Review by dansible — APPROVED** [review]

**Pull request merged**
