### PR TITLE
upgrade gardener v1.5.0 and make revendor

### LINKED ISSUE #241: upgrade gardener/gardener version to at least v1.5.0 for gardenctl
from discussion [here](https://github.com/gardener/gardenctl/issues/232#issuecomment-667014548) , currently in gardenctl the gardener version is v1.1.6, in issue https://github.com/gardener/gardenctl/issues/232 we need to utilize some api in gardener/gardener >= v1.5.0, so we need to upgrade g/g to at least v1.5.0 in gardenctl

### PR DESCRIPTION
**Pull request by neo-liang-sap**
**What this PR does / why we need it**:
upgrade gardener/gardener version to v1.5.0 
**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardenctl/issues/241

**Special notes for your reviewer**:
after i modified gardener version in `go.mod`, then i run `make revendor` 
**Release note**:
```improvement operator
upgrade gardener/gardener version to v1.5.0 
```

### CODE REVIEW

**Comment by neo-liang-sap** [comment]
Hi @DockToFuture ,
For this PR i modified `go.mod` to update gardener version to v1.5.0 and then i run `make revendor`
then I `git add` all files updated in `vendor` folder
Are these steps correct?

Thanks.
-Neo

**Comment by neo-liang-sap** [comment]
after upgraded to v1.5.0 the gardenctl can't build, investigating
```
.ci/build                                                                                            
# github.com/gardener/gardenctl/pkg/cmd
pkg/cmd/ls.go:255:33: cannot use item.Status.LastOperation.Progress (type int32) as type int in assignment
pkg/cmd/ls.go:261:70: lastError.GetDescription undefined (type "github.com/gardener/gardener/pkg/apis/core/v1beta1".LastError has no field or method GetDescription)
note: module requires Go 1.14
```

**Comment by neo-liang-sap** [comment]
Hello @DockToFuture ,
For upgrading `g/g` version from `v1.1.6` to `v1.5.0`, i performed following steps:
1) change version number for `g/g` in go.mod
2) run `make revendor`
3) fix two api changes from `v1.1.6` to `v1.5.0`

then i can `make build` success in my local env, but when i pushed to github, CI failed complaining all `## explicit` directives are removed from `vendor/modules.txt`

then i manually added the missing `## explicit` to modules.txt, the `missing explicit` error is fixed, but CI is reporting error regarding `replace` directives
https://concourse.ci.gardener.cloud/teams/gardener/pipelines/gardenctl-master/jobs/master-pull-request-job/builds/14
```
go: inconsistent vendoring in /tmp/build/a94a8fe5/pull-request-gardener_gardenctl-pr_master:
	k8s.io/api: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/apimachinery: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/client-go: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	github.com/evanphx/json-patch@v4.5.0+incompatible: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
```
i tried add sth like `## replaced` to `k8s.io/api` but seems not help

My questions are:
- are my steps (from 1) to 3)) correct?
- how can i fix the `xxx is replaced in go.mod, but not marked as replaced in vendor/modules.txt`?

Thanks!

/CC @dansible

**Comment by neo-liang-sap** [comment]
Hello @DockToFuture ,
For upgrading `g/g` version from `v1.1.6` to `v1.5.0`, i performed following steps:
1) change version number for `g/g` in go.mod
2) run `make revendor`
3) fix two api changes from `v1.1.6` to `v1.5.0`

then i can `make build` success in my local env, but when i pushed to github, CI failed complaining all `## explicit` directives are removed from `vendor/modules.txt`

then i manually added the missing `## explicit` to modules.txt, the `missing explicit` error is fixed, but CI is reporting error regarding `replace` directives
https://concourse.ci.gardener.cloud/teams/gardener/pipelines/gardenctl-master/jobs/master-pull-request-job/builds/14
```
go: inconsistent vendoring in /tmp/build/a94a8fe5/pull-request-gardener_gardenctl-pr_master:
	k8s.io/api: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/apimachinery: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/client-go: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	github.com/evanphx/json-patch@v4.5.0+incompatible: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
```
i tried add sth like `## replaced` to `k8s.io/api` but seems not help

My questions are:
- are my steps (from 1) to 3)) correct?
- how can i fix the `xxx is replaced in go.mod, but not marked as replaced in vendor/modules.txt`?

Thanks!

/CC @dansible

**Comment by neo-liang-sap** [comment]
Hello @DockToFuture ,
For upgrading `g/g` version from `v1.1.6` to `v1.5.0`, i performed following steps:
1) change version number for `g/g` in go.mod
2) run `make revendor`
3) fix two api changes from `v1.1.6` to `v1.5.0`

then i can `make build` success in my local env, but when i pushed to github, CI failed complaining all `## explicit` and `replace` directives are removed from `vendor/modules.txt`

4) then i manually added back the `## explicit` and append following lines at end of `modules.txt`
```
# k8s.io/api => k8s.io/api v0.0.0-20190918155943-95b840bb6a1f
# k8s.io/apimachinery => k8s.io/apimachinery v0.0.0-20190913080033-27d36303b655
# k8s.io/client-go => k8s.io/client-go v0.0.0-20190918160344-1fbdaa4c8d90
```

then CI build success

My above steps are correct? do let me know if any step is wrong...

/CC @dansible 

Thanks!
-Neo

**Review by DockToFuture — APPROVED** [review]
/lgtm

The steps are correct.

**Pull request merged**
