### PR TITLE
Vpn seed logs

### LINKED ISSUE #355: Enable `gardenctl logs vpn-seed`
Enable the logs of the vpn-seed

### PR DESCRIPTION
**Pull request by jguipi**
**What this PR does / why we need it**:
add gardenctl logs vpn-seed to display vpn-seed logs

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardenctl/issues/355

**Special notes for your reviewer**:

**Release note**:
add `gardenctl logs vpn-seed <namespace>` to display vpn-seed logs

### CODE REVIEW

**Comment by gardener-robot-ci-3** [comment]
Thank you @jguipi for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by neo-liang-sap** [comment]
Hi @jguipi , thanks for the PR!
could you please get rid of this commit from this PR? this is just a merging history which doesn't contains any code change
image

**Comment by neo-liang-sap** [comment]
@jguipi 
1) please remove dummy commit https://github.com/gardener/gardenctl/pull/357/commits/861e62c943361f74adf2928b99f712fd02b34b34
2) squash several commits into one commit in this PR

otherwise LGTM

**Comment by neo-liang-sap** [comment]
Hi @jguipi , please fix the conflicts in `pkg/cmd/logs.go`

**Pull request closed without merging**
